In [1]:
from aquacrop import AquaCropModel, Soil, Crop, InitialWaterContent, FieldMngt, GroundWater
from aquacrop.utils import prepare_weather, get_filepath

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
# locate built in weather file
filepath = get_filepath("tunis_climate.txt")

weather_data = prepare_weather(filepath)
weather_data

      MinTemp  MaxTemp  Precipitation  ReferenceET       Date
0        15.0     20.0            0.0          1.5 1979-01-01
1         8.0     15.0            0.0          1.3 1979-01-02
2         3.0     12.0            0.0          1.2 1979-01-03
3         5.0     19.0            0.0          1.8 1979-01-04
4        10.0     17.0            0.0          1.4 1979-01-05
...       ...      ...            ...          ...        ...
8547     17.3     32.5            0.0          7.0 2002-05-27
8548     16.8     24.4            0.0          4.9 2002-05-28
8549     15.0     27.8            0.0          6.0 2002-05-29
8550     14.1     30.0            0.0          6.4 2002-05-30
8551     17.0     29.2            0.0          5.9 2002-05-31

[8552 rows x 5 columns]

In [3]:
sandy_loam = Soil(soil_type="SandyLoam")

In [11]:
sandy_loam.profile.dzsum

0     0.1
1     0.2
2     0.3
3     0.4
4     0.5
5     0.6
6     0.9
7     1.2
8     1.5
9     1.8
10    2.1
11    2.4
Name: dzsum, dtype: float64

In [5]:
wheat = Crop("Maize", planting_date="10/01")

In [6]:
wheat.planting_date

'10/01'

In [7]:
InitWC = InitialWaterContent(value=["FC"])

In [8]:
# combine into aquacrop model and specify start and end simulation date
model = AquaCropModel(
    sim_start_time=f"{1979}/09/01",
    sim_end_time=f"{1985}/05/30",
    weather_df=weather_data,
    soil=sandy_loam,
    crop=wheat,
    initial_water_content=InitWC,
)

In [9]:
# run model till termination
model.run_model(till_termination=True)

TMAX : 30.0
TMIN : 23.0
PRECIP : 0.0
ET0 : 4.0
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.18674788 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 23.0
PRECIP : 0.0
ET0 : 4.1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.16484379 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 30.0
TMIN : 17.0
PRECIP : 0.0
ET0 : 4.7
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.14673291 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 30.0
TMIN : 19.0
PRECIP : 0.0
ET0 : 4.7
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.13284435 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 28.0
TMIN : 17.0
PRECIP : 0.0
ET0 : 4.2
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.12270963 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 17.0
PRECIP : 0.0
ET0 : 4.4
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.11369512 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 24.0
TMIN : 21.0
PRECIP : 0.0
ET0 : 2.4
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.10932054 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 17.0
PRECIP : 1.5
ET0 : 4.1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.09852261 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 30.0
TMIN : 22.0
PRECIP : 0.0
ET0 : 4.3
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.08559368 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 28.0
TMIN : 17.0
PRECIP : 0.0
ET0 : 4.0
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.07631185 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 18.0
PRECIP : 0.0
ET0 : 4.2
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.06837028 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 30.0
TMIN : 20.0
PRECIP : 0.0
ET0 : 4.4
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.06142348 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 30.0
TMIN : 19.0
PRECIP : 0.7
ET0 : 4.3
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.05643347 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 18.0
PRECIP : 7.8
ET0 : 3.8
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.09263347 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 30.0
TMIN : 19.0
PRECIP : 0.0
ET0 : 4.1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.0621064 0.22      0.22      0.22      0.22      0.22      0.22
 0.22      0.22      0.22      0.22      0.22     ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 19.0
PRECIP : 0.0
ET0 : 3.9
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.05672879 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 18.0
PRECIP : 0.0
ET0 : 3.9
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.0519922 0.22      0.22      0.22      0.22      0.22      0.22
 0.22      0.22      0.22      0.22      0.22     ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 31.0
TMIN : 18.0
PRECIP : 0.0
ET0 : 4.5
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.05       0.21710693 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 32.0
TMIN : 23.0
PRECIP : 0.0
ET0 : 4.5
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.05       0.21253781 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 31.0
TMIN : 19.0
PRECIP : 0.0
ET0 : 4.4
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.05       0.20831973 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 27.0
TMIN : 18.0
PRECIP : 18.9
ET0 : 3.4
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.2016     0.20831973 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 27.0
TMIN : 18.0
PRECIP : 0.5
ET0 : 3.5
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.17519035 0.20831973 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 21.0
TMIN : 14.0
PRECIP : 21.3
ET0 : 2.4
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.35571263 0.20831973 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 24.0
TMIN : 13.0
PRECIP : 8.7
ET0 : 3.3
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.27348516 0.22422483 0.22392036 0.2229626  0.22232263 0.22189271
 0.22158932 0.22105349 0.22077994 0.22061563 0.2205066  0.22042924]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 25.0
TMIN : 14.0
PRECIP : 0.0
ET0 : 3.5
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.18535541 0.22359807 0.22217904 0.22158304 0.22125051 0.22103649
 0.22088656 0.22062443 0.22048319 0.22039461 0.22033376 0.22028933]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 25.0
TMIN : 14.0
PRECIP : 0.0
ET0 : 3.5
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.15863459 0.22032511 0.2201983  0.22017557 0.22016704 0.22015547
 0.2201444  0.22012128 0.22010372 0.22009069 0.22008073 0.22007287]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 23.0
TMIN : 15.0
PRECIP : 1.3
ET0 : 3.0
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.14140076 0.22002986 0.22001822 0.22001614 0.22001606 0.22001591
 0.22001561 0.22001475 0.22001376 0.22001283 0.22001201 0.22001129]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 24.0
TMIN : 13.0
PRECIP : 4.9
ET0 : 3.0
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.15740076 0.22000275 0.22000168 0.22000148 0.22000148 0.22000148
 0.22000147 0.22000146 0.22000143 0.2200014  0.22000136 0.22000132]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 23.0
TMIN : 17.0
PRECIP : 5.6
ET0 : 2.5
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.18590076 0.22000025 0.22000015 0.22000014 0.22000014 0.22000014
 0.22000014 0.22000014 0.22000014 0.22000013 0.22000013 0.22000013]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 24.5
TMIN : 17.0
PRECIP : 0.0
ET0 : 3.0
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.0
[0.15306871 0.22000002 0.22000001 0.22000001 0.22000001 0.22000001
 0.22000001 0.22000001 0.22000001 0.22000001 0.22000001 0.22000001]
0.1
0.3
5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 26.0
TMIN : 17.0
PRECIP : 0.0
ET0 : 3.4
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.3
[0.19077646 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 25.0
TMIN : 15.0
PRECIP : 0.0
ET0 : 3.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.3
[0.17307285 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 25.0
TMIN : 15.0
PRECIP : 0.0
ET0 : 2.9
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.3
[0.15977257 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 14.0
PRECIP : 0.0
ET0 : 3.6
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.3
[0.14649658 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 19.0
PRECIP : 0.0
ET0 : 3.6
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.3092994451805572
[0.13563303 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 27.0
TMIN : 17.0
PRECIP : 0.0
ET0 : 3.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.34564432745689355
[0.12769021 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 26.0
TMIN : 15.0
PRECIP : 1.2
ET0 : 2.8
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.37924208111820945
[0.11728463 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 25.0
TMIN : 15.0
PRECIP : 0.0
ET0 : 2.6
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.4109345048110951
[0.10498317 0.22       0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 28.0
TMIN : 17.0
PRECIP : 0.0
ET0 : 3.1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.44118687349100594
[0.09406797 0.21955697 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 21.0
PRECIP : 0.0
ET0 : 3.3
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.4702919291719444
[0.08491659 0.21900282 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 28.0
TMIN : 20.0
PRECIP : 0.0
ET0 : 3.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.4984495675594254
[0.07808152 0.21841072 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 14.0
PRECIP : 0.0
ET0 : 3.2
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.525804261690775
[0.07189851 0.21766878 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 29.0
TMIN : 15.0
PRECIP : 0.0
ET0 : 3.4
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.5524648919321966
[0.06627245 0.21674337 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 31.0
TMIN : 18.0
PRECIP : 0.0
ET0 : 3.5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.5785161990403724
[0.0612676  0.21562545 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 25.0
TMIN : 18.0
PRECIP : 0.0
ET0 : 2.5
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.6040258430012962
[0.05810157 0.21468718 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 33.0
TMIN : 14.0
PRECIP : 0.0
ET0 : 3.9
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.6290489806918148
[0.05369095 0.21297152 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 34.0
TMIN : 17.0
PRECIP : 0.0
ET0 : 4.1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
beginning
<aquacrop.entities.soilProfile.SoilProfile object at 0x7612cafd8830>
0.6536313587778121
[0.05       0.21051058 0.22       0.22       0.22       0.22
 0.22       0.22       0.22       0.22       0.22       0.22      ]
0.1
0.3
5.0
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
TMAX : 25.0
TMIN : 19.0
PRECIP : 0.0
ET0 : 2.1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1
[0.1 0.2 0.3 0.4 0.5 0.6 0.9 1.2 1.5 1.8 2.1 2.4]
0.1
1
0.1

True

In [8]:
# model._outputs.water_flux.head()
# model._outputs.water_storage.head()
# model._outputs.crop_growth.head()
model._outputs.final_stats.head()

,Season,crop Type,Harvest Date (YYYY/MM/DD),Harvest Date (Step),Dry yield (tonne/ha),Fresh yield (tonne/ha),Yield potential (tonne/ha),Seasonal irrigation (mm)
0,0,Wheat,1980-04-15,196,8.940140,9.933489,8.945246,0
1,1,Wheat,1981-04-16,562,8.309577,9.232863,8.314556,0
2,2,Wheat,1982-04-16,927,9.136122,10.151246,9.141264,0
3,3,Wheat,1983-04-16,1292,8.811568,9.790631,8.816327,0
4,4,Wheat,1984-04-15,1657,8.682660,9.647400,8.687385,0